imeta:
  config:
    meta-path: '${static.path}/models/*.xml'
    trim-path: '/models/'
    load-type: RES
  orm:
    dialect: mysql
    func:
      signatures:
      - 'String date_format(DateTime,String)'
      - 'Any concat(Any...)'
      - 'Number count(Any)'
      - 'Number sum(Number)'
      - 'Any max(Any)'
      - 'Any min(Any)'
      complexes:
      - alias: distinct
        signature: Any distinct(Any...)
#        prefix: ''
#        suffix: ''
      - alias: count(distinct
        signature: 'Number count_distinct(Any...)'
#        prefix: ''
        suffix: ')'
    id:
      data-center-id: ${id.center:1}
      worker-id: ${id.worker:1}
#  profile:
#    domain-databases:
#      default: ${db.database}
#    type: oneInstance
  redis:
    type: jedis #lettuce
    password: ${redis.pwd}
    database: ${redis.db:0}
  schedule:
    auto-start: true
    startup-delay: 0
    props:
      org.quartz.scheduler.instanceName: QuartzScheduler
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 10
      org.quartz.threadPool.threadPriority: 5
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
  mail:
    default:
      contentType: html
      from: ${mail.from:zhaoyf@yonyou.com}
      subject: ${mail.topic}
      to: ${mail.to:zhaoyf@yonyou.com}
    smtp:
      host: ${mail.host:mail.yonyou.com}
      port: 25
      auth: true
      username: ${mail.username:zhaoyf@yonyou.com}
      password: ${mail.pwd}
  tpl:
    tpl-paths:
    - path: '${static.path}/tpl/**/*.tpl'
      trim: '/tpl/'
    - path: '${static.path}/query/*.tpl'
      trim: '/query/'
    dst-base-path: '${code.path}'
    code-dst-path: 'src/main/java/{NAME_SPACE_PATH}/{moduleName}/{name}'
    code-proj-dst-path: 'src/main/java/{NAME_SPACE_PATH}/{moduleName}/{name}'
    res-dst-path: '${res.path}'
    db-dialect: mysql
    target-framework: java
    parameters:
      NAME_SPACE: 'com.smart.cloud.mall.model'
      NAME_SPACE_PATH: 'com/smart/cloud/mall/model'
      AUTHOR: 'zhaoyanfeng'
      VERSION: '1.0'
      CURRENT_DATE: '_CURRENT_DATE_'
    templates:
      ENTITY_TPL_KEY: '%fw/entity.tpl'
      INTERFACE_TPL_KEY: '%fw/interface.tpl'
      ENUM_TPL_KEY: '%fw/enum.tpl'
      DAO_TPL_KEY: '%fw/%db/dao.tpl'
      SERVICE_TPL_KEY: '%fw/controller.tpl'
      TABLE_TPL_KEY: '%db/table.tpl'
      QUERY_SCHEMA_TPL_KEY: 'query_schema.tpl'
      ASSOCIATION_TPL_KEY: 'asso.tpl'
      API_DOC_TPL_KEY: 'api_doc.tpl'
      ENTITY_DOC_TPL_KEY: 'entity_doc.tpl'
      ENTITY_INDEX_DOC_TPL_KEY: 'entity_index_doc.tpl'
      ENTITY_TEST_DATA_TPL_KEY: 'entity_test_data_json.tpl'
  export:
    tpl-path: '${static.path}/export'
  query:
    schema-path: '${static.path}/query'
    format-path: '${static.path}/query'
    trim-path: '/query/'
  authentication:
    enabled: ${auth.enabled:true}
    api:
      skip-check: ${api.skip.check:false}
      header-key: ${api.header.key:X-META-STARTER-TOKEN}
      tolerance-milli: ${api.tolerance.milli:120000}
      app-secrete: "APP-SECRET"
    session:
        expires: 3600
        sliding: true
        token-key: token
        session-id: ${auth.session.id:startersessionid}
        cookie-path: '/'
        auth-attribute-key: 'AUTHENTICATION-TOKEN'
    excludes:
#      - '/mdd/q/find/login'
      - '/user/login'
      - '/error'
      - '~ \.\w+$'
    pages:
      index-page: 'index.html'
      login-page: 'login.html'
    cors:
      enabled: ${cors.enabled:false}
      allowedOrigin: "*"
      allowedHeader: "*"
      allowedMethods: "*"
      maxAge: ${cors.max.age:3600}
      allowCredentials: ${cors.allow.credentials:true}
org:
  imeta:
    spring:
      config:
        ExternalImportRegistrar: com.imeta.cloud.mall.service.config.MallConfig